spring.application.name=todo

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SYSTEM
spring.datasource.password=system
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meliora945@gmail.com
spring.mail.password=mvkkzudfxlltaoby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
	
spring.ai.google.gemini.api-key=AIzaSyACNS7qm2IjtoI-mdyH-w-6zVLFq84qpsk
spring.ai.google.gemini.chat.options.model=gemini-2.5-flash
# --- File Upload Configuration ---

# Set the maximum size for a single file (e.g., 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Set the maximum size for the total request (can include multiple files)
# This should be slightly larger than or equal to max-file-size
spring.servlet.multipart.max-request-size=12MB

 
