spring.application.name=todo
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SYSTEM
spring.datasource.password=system
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meliora945@gmail.com
spring.mail.password=mvkkzudfxlltaoby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# gemini.api.key=AIzaSyA1mlaph9IlgHqLCg1qT-EWsgd0Ja4HlbA

# Google Gemini Config
spring.ai.google.genai.api-key=AIzaSyA1mlaph9IlgHqLCg1qT-EWsgd0Ja4HlbA
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
#spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.chat.options.temperature=0.7
# spring.ai.google.genai.chat.options.model=gemini-pro

# spring.ai.openai.api-key=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
# spring.ai.openai.chat.options.model=gpt-3.5-turbo
# spring.ai.openai.chat.options.temperature=0.7

# Logging (Optional: helpful to see the function calls in the console)
logging.level.org.springframework.ai=DEBUG

# --- File Upload Configuration ---

# Set the maximum size for a single file (e.g., 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Set the maximum size for the total request (can include multiple files)
# This should be slightly larger than or equal to max-file-size
spring.servlet.multipart.max-request-size=12MB

 
